<?php

namespace Database\Seeders;

use App\Models\KlasifikasiSurat;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KlasifikasiSuratSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
                ['kode' => '000', 'nama' => 'Umum', 'parent' => null], // << Tambahkan ini di paling awal

                    // Klasifikasi Surat Umum        
                ['kode' => '000.1', 'nama' => 'KETATAUSAHAAN DAN KERUMAHTANGGAAN', 'parent' => null],
                ['kode' => '000.1.1', 'nama' => 'Telekomunikasi', 'parent' => '000.1'],
                ['kode' => '000.1.2', 'nama' => 'Perjalanan Dinas Dalam Negeri', 'parent' => '000.1'],
                ['kode' => '000.1.2.1', 'nama' => 'Perjalanan Dinas Kepala Daerah', 'parent' => '000.1.2'],
                ['kode' => '000.1.2.2', 'nama' => 'Perjalanan Dinas DPRD', 'parent' => '000.1.2'],
                ['kode' => '000.1.2.3', 'nama' => 'Perjalanan Dinas Pegawai', 'parent' => '000.1.2'],
                ['kode' => '000.1.3', 'nama' => 'Perjalanan Dinas Luar Negeri', 'parent' => '000.1'],
                ['kode' => '000.1.3.1', 'nama' => 'Perjalanan Dinas Kepala Daerah', 'parent' => '000.1.3'],
                ['kode' => '000.1.3.2', 'nama' => 'Perjalanan Dinas DPRD', 'parent' => '000.1.3'],
                ['kode' => '000.1.3.3', 'nama' => 'Perjalanan Dinas Pegawai', 'parent' => '000.1.3'],
                ['kode' => '000.1.4', 'nama' => 'Penggunaan Fasilitas Kantor (antara lain: Permintaan dan penggunaan ruang, gedung, kendaraan, wisma, rumah dinas dan fasilitas kantor lainnya)', 'parent' => '000.1'],
                ['kode' => '000.1.5', 'nama' => 'Rapat pimpinan antara lain: Notula/Risalah Rapat', 'parent' => '000.1'],
                ['kode' => '000.1.6', 'nama' => 'Penyediaan Konsumsi', 'parent' => '000.1'],
                ['kode' => '000.1.7', 'nama' => 'Pengurusan Kendaraan Dinas', 'parent' => '000.1'],
                ['kode' => '000.1.7.1', 'nama' => 'Pengurusan surat-surat kendaraan dinas', 'parent' => '000.1.7'],
                ['kode' => '000.1.7.2', 'nama' => 'Pemeliharaan dan perbaikan', 'parent' => '000.1.7'],
                ['kode' => '000.1.7.3', 'nama' => 'Pengurusan kehilangan dan masalah kendaraan', 'parent' => '000.1.7'],
                ['kode' => '000.1.8', 'nama' => 'Pemeliharaan Gedung, Taman dan Peralatan Kantor', 'parent' => '000.1'],
                ['kode' => '000.1.8.1', 'nama' => 'Pertamanan/ Landscape', 'parent' => '000.1.8'],
                ['kode' => '000.1.8.2', 'nama' => 'Penghijauan', 'parent' => '000.1.8'],
                ['kode' => '000.1.8.3', 'nama' => 'Perbaikan Gedung', 'parent' => '000.1.8'],
                ['kode' => '000.1.8.4', 'nama' => 'Perbaikan Peralatan Kantor', 'parent' => '000.1.8'],
                ['kode' => '000.1.8.5', 'nama' => 'Perbaikan Rumah Dinas/Wisma', 'parent' => '000.1.8'],
                ['kode' => '000.1.8.6', 'nama' => 'Kebersihan Gedung dan Taman', 'parent' => '000.1.8'],
                ['kode' => '000.1.9', 'nama' => 'Pengelolaan Jaringan Listrik, Air, Telepon dan Komputer', 'parent' => '000.1'],
                ['kode' => '000.1.9.1', 'nama' => 'Perbaikan / Pemeliharaan', 'parent' => '000.1.9'],
                ['kode' => '000.1.9.2', 'nama' => 'Pemasangan', 'parent' => '000.1.9'],
                ['kode' => '000.1.10', 'nama' => 'Ketertiban dan Keamanan', 'parent' => '000.1'],
                ['kode' => '000.1.10.1', 'nama' => 'Pengamanan, Penjagaan, dan Pengawalan terhadap Pejabat, Kantor dan Rumah Dinas', 'parent' => '000.1.10'],
                ['kode' => '000.1.10.2', 'nama' => 'Laporan Ketertiban dan Keamanan', 'parent' => '000.1.10'],
                ['kode' => '000.1.11', 'nama' => 'Administrasi Pengelolaan Parkir', 'parent' => '000.1'],
                ['kode' => '000.1.12', 'nama' => 'Administrasi Pakaian Dinas Pegawai, Satpam, Petugas Kebersihan dan Pegawai lainnya', 'parent' => '000.1'],

                ['kode' => '000.2', 'nama' => 'PERLENGKAPAN', 'parent' => null],
                ['kode' => '000.2.1', 'nama' => 'Inventarisasi dan Penyimpanan', 'parent' => '000.2'],
                ['kode' => '000.2.1.1', 'nama' => 'Data hasil inventarisasi dan penyimpanan', 'parent' => '000.2.1'],
                ['kode' => '000.2.1.2', 'nama' => 'Laporan dan evaluasi inventarisasi dan penyimpanan', 'parent' => '000.2.1'],
                ['kode' => '000.2.2', 'nama' => 'Pemeliharaan peralatan kantor', 'parent' => '000.2'],
                ['kode' => '000.2.2.1', 'nama' => 'Data hasil pemeliharaan kantor', 'parent' => '000.2.2'],
                ['kode' => '000.2.2.2', 'nama' => 'Laporan dan evaluasi pemeliharaan kantor', 'parent' => '000.2.2'],
                ['kode' => '000.2.3', 'nama' => 'Distribusi', 'parent' => '000.2'],
                ['kode' => '000.2.3.1', 'nama' => 'Barang habis pakai', 'parent' => '000.2.3'],
                ['kode' => '000.2.3.2', 'nama' => 'Barang milik daerah', 'parent' => '000.2.3'],
                ['kode' => '000.2.4', 'nama' => 'Penghapusan Barang Milik Daerah antara lain: Keputusan Pembentukan Tim, Berita Acara Penghapusan Barang Milik Daerah, Daftar Barang yang dihapuskan, Laporan Hasil Pelaksanaan Penghapusan BMD termasuk didalamnya proses lelang penghapusan', 'parent' => '000.2'],
                ['kode' => '000.2.5', 'nama' => 'Pengelolaan Database Barang Milik Daerah', 'parent' => '000.2'],

                ['kode' => '000.3', 'nama' => 'PENGADAAN', 'parent' => null],
                ['kode' => '000.3.1', 'nama' => 'Rencana pengadaan barang dan jasa (antara lain: Identifikasi dan analisis kebutuhan barang/jasa, penyusunan dan penetapan rencana penganggaran pengadaan, penetapan kebijakan umum, penyusunan kerangka Acuan Kerja (KAK), Pengumuman Rencana Umum Pengadaan)', 'parent' => '000.3'],
                ['kode' => '000.3.2', 'nama' => 'Pengadaan Langsung (antara lain: persiapan pemilihan penyedia, pelaksanaan pemilihan penyedia, penandatanganan kontrak, pelaksanaan kontrak)', 'parent' => '000.3'],
                ['kode' => '000.3.3', 'nama' => 'Pengadaan Tidak Langsung/Lelang (antara lain: persiapan pemilihan penyedia, pelaksanaan pemilihan penyedia, penandatanganan kontrak, pelaksanaan kontrak)', 'parent' => '000.3'],
                ['kode' => '000.3.4', 'nama' => 'Swakelola (antara lain: perencanaan, pelaksanaan dan evaluasi)', 'parent' => '000.3'],
                ['kode' => '000.3.5', 'nama' => 'Pengolahan Sistem Informasi Pengadaan antara lain: Data base pengguna sistem informasi pengadaan barang/jasa, Data Base kontrak, Data Base Pengadaan Barang/jasa', 'parent' => '000.3'],
                ['kode' => '000.3.6', 'nama' => 'Monitoring dan evaluasi pelaksanaan kebijakan dan pelaksanaan pengadaan antara lain: Laporan Hasil Monitoring, Laporan hasil evaluasi', 'parent' => '000.3'],
                    // Klasifikasi Surat Dinas
                ['kode' => '400.12', 'nama' => 'KEPENDUDUKAN DAN CATATAN SIPIL', 'parent' => null],
                ['kode' => '400.12.1', 'nama' => 'Kebijakan di bidang Kependudukan dan Catatan Sipil yang dilakukan oleh Pemerintah Daerah', 'parent' => '400.12'],
                ['kode' => '400.12.2', 'nama' => 'Pendaftaran Penduduk', 'parent' => '400.12'],
                ['kode' => '400.12.2.1', 'nama' => 'Identitas Penduduk', 'parent' => '400.12.2'],
                ['kode' => '400.12.2.2', 'nama' => 'Pindah Datang Penduduk Dalam Wilayah NKRI', 'parent' => '400.12.2'],
                ['kode' => '400.12.2.3', 'nama' => 'Pindah Datang Penduduk Antar Negara', 'parent' => '400.12.2'],
                ['kode' => '400.12.2.4', 'nama' => 'Pendataan Penduduk Rentan', 'parent' => '400.12.2'],
                ['kode' => '400.12.2.5', 'nama' => 'Monitoring Evaluasi dan Dokumentasi', 'parent' => '400.12.2'],
                ['kode' => '400.12.3', 'nama' => 'Pencatatan Sipil', 'parent' => '400.12'],
                ['kode' => '400.12.3.1', 'nama' => 'Kelahiran dan Kematian', 'parent' => '400.12.3'],
                ['kode' => '400.12.3.2', 'nama' => 'Perkawinan dan Perceraian', 'parent' => '400.12.3'],
                ['kode' => '400.12.3.3', 'nama' => 'Pengangkatan Pengakuan dan Pengesahan Anak serta Perubahan', 'parent' => '400.12.3'],
                ['kode' => '400.12.3.4', 'nama' => 'Pencatatan Kewarganegaraan', 'parent' => '400.12.3'],
                ['kode' => '400.12.3.5', 'nama' => 'Monitoring Evaluasi dan Dokumentasi', 'parent' => '400.12.3'],
                ['kode' => '400.12.4', 'nama' => 'Pengelolaan Informasi Administrasi Kependudukan', 'parent' => '400.12'],
                ['kode' => '400.12.4.1', 'nama' => 'Sistem Informasi Administrasi Kependudukan', 'parent' => '400.12.4'],
                ['kode' => '400.12.4.2', 'nama' => 'Kelembagaan Informasi Administrasi Kependudukan', 'parent' => '400.12.4'],
                ['kode' => '400.12.4.3', 'nama' => 'Pengelolaan data Administrasi Kependudukan', 'parent' => '400.12.4'],
                ['kode' => '400.12.4.4', 'nama' => 'Penyajian dan Layanan Informasi Administrasi Kependudukan', 'parent' => '400.12.4'],
                ['kode' => '400.12.4.5', 'nama' => 'Monitoring Evaluasi dan Dokumentasi', 'parent' => '400.12.4'],
                ['kode' => '400.12.5', 'nama' => 'Pengembangan Kebijakan Kependudukan', 'parent' => '400.12'],
                ['kode' => '400.12.5.1', 'nama' => 'Kuantitas Penduduk', 'parent' => '400.12.5'],
                ['kode' => '400.12.5.2', 'nama' => 'Kualitas Penduduk', 'parent' => '400.12.5'],
                ['kode' => '400.12.5.3', 'nama' => 'Mobilitas Penduduk', 'parent' => '400.12.5'],
                ['kode' => '400.12.5.4', 'nama' => 'Perlindungan dan Pemberdayaan Penduduk', 'parent' => '400.12.5'],
                ['kode' => '400.12.5.5', 'nama' => 'Pengembangan Wawasan Kependudukan, Monitoring dan Evaluasi', 'parent' => '400.12.5'],
                ['kode' => '400.12.6', 'nama' => 'Penyerasian Kependudukan', 'parent' => '400.12'],
                ['kode' => '400.12.6.1', 'nama' => 'Indikator Kependudukan', 'parent' => '400.12.6'],
                ['kode' => '400.12.6.2', 'nama' => 'Proyeksi Penduduk', 'parent' => '400.12.6'],
                ['kode' => '400.12.6.3', 'nama' => 'Perencanaan Kependudukan', 'parent' => '400.12.6'],
                ['kode' => '400.12.6.4', 'nama' => 'Penyerasian Kebijakan Kependudukan dengan Lembaga Non Pemerintah', 'parent' => '400.12.6'],
                ['kode' => '400.12.6.5', 'nama' => 'Pelaksanaan Penyerasian Kebijakan Kependudukan dengan Lembaga Pemerintah', 'parent' => '400.12.6'],
                   // Klasifikasi Surat Kepegawaian
                ['kode' => '800', 'nama' => 'KEPEGAWAIAN', 'parent' => null],
                ['kode' => '800.1', 'nama' => 'SUMBER DAYA MANUSIA', 'parent' => '800'],
                ['kode' => '800.1.1', 'nama' => 'Penyusunan dan Penetapan Kebutuhan Aparatur Sipil Negara', 'parent' => '800.1'],
                ['kode' => '800.1.1.1', 'nama' => 'Perencanaan Kebutuhan Aparatur Sipil Negara Antara lain: Bahan penyusunan rencana kebutuhan, Analisis Kebutuhan, Pengolahan data kebutuhan', 'parent' => '800.1.1'],
                ['kode' => '800.1.1.2', 'nama' => 'Perencanaan Pertimbangan Formasi Antara lain: Pertimbangan teknis penetapan formasi Pertimbangan teknis formasi ikatan dinas ASN, penetapan', 'parent' => '800.1.1'],
                ['kode' => '800.1.1.3', 'nama' => 'Penetapan Kebutuhan Aparatur Sipil Negara', 'parent' => '800.1.1'],
                ['kode' => '800.1.1.4', 'nama' => 'Standarisasi Jabatan Antara lain: Informasi Jabatan, Kompetensi Jabatan, Klasifikasi Jabatan', 'parent' => '800.1.1'],
                ['kode' => '800.1.2', 'nama' => 'Formasi dan Pengadaan Pegawai', 'parent' => '800.1'],
                ['kode' => '800.1.2.1', 'nama' => 'Formasi ASN Antara lain: Usulan formasi, Usulan permintaan formasi kepada Menpan RB dan Kepala BKN, Persetujuan Formasi, Penetapan Formasi, Penetapan Formasi Khusus', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.2', 'nama' => 'Proses Rekrutmen/Pengadaan ASN Antara lain: Proses Rekrutmen ASN, Penetapan Pengumuman Kelulusan ASN', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.3', 'nama' => 'Pengumuman Kelulusan ASN', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.4', 'nama' => 'Berkas Lamaran Yang Tidak Diterima', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.5', 'nama' => 'Pengangkatan ASN', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.6', 'nama' => 'Open Biding (Seleksi Terbuka Jabatan)', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.7', 'nama' => 'Pengelolaan Sistem Rekrutmen ASN', 'parent' => '800.1.2'],
                ['kode' => '800.1.2.8', 'nama' => 'Fasilitasi ASN Penyelenggaraan Seleksi', 'parent' => '800.1.2'],
                ['kode' => '800.1.3', 'nama' => 'Mutasi Pegawai', 'parent' => '800.1'],
                ['kode' => '800.1.3.1', 'nama' => 'Usulan Alih Status, Pindah Instansi, Pindah Wilayah Diperbantukan, Kerja, Dipekerjakan, Penugasan Sementara, Mutasi antar Perwakilan, Mutasi ke dan dari Perwakilan, Pemindahan Sementara, Persetujuan/Pertimbangan Kepala BKN', 'parent' => '800.1.3'],
                ['kode' => '800.1.3.2', 'nama' => 'Kenaikan Pangkat/Golongan/Jabatan', 'parent' => '800.1.3'],
                ['kode' => '800.1.3.3', 'nama' => 'Pengangkatan dan Pemberhentian Jabatan Struktural/Fungsional', 'parent' => '800.1.3'],
                ['kode' => '800.1.3.4', 'nama' => 'Perubahan Data Dasar/ Status/Kedudukan Hukum Pegawai', 'parent' => '800.1.3'],
                ['kode' => '800.1.3.5', 'nama' => 'Peninjauan Masa Kerja', 'parent' => '800.1.3'],
                ['kode' => '800.1.3.6', 'nama' => 'Badan Pertimbangan Jabatan dan Pangkat (BAPERJAKAT)', 'parent' => '800.1.3'],
                ['kode' => '800.1.4', 'nama' => 'Pengembangan Karir', 'parent' => '800.1'],
                ['kode' => '800.1.4.1', 'nama' => 'Usulan Tugas Belajar/ Ijin Belajar/ Diklat/ Kursus/ Magang/ Ujian Dinas/ Praktek Kerja di Instansi lain/ Pertukaran antar ASN dengan pegawai swasta', 'parent' => '800.1.4'],
                ['kode' => '800.1.4.2', 'nama' => 'Penyesuaian ijazah', 'parent' => '800.1.4'],
                ['kode' => '800.1.4.3', 'nama' => 'Penyusunan Sistem Karier', 'parent' => '800.1.4'],
                ['kode' => '800.1.4.4', 'nama' => 'Standar Kinerja Pegawai (SKP) dan Penilaian Prestasi Kerja', 'parent' => '800.1.4'],
                ['kode' => '800.1.4.5', 'nama' => 'Angka Kredit Antara lain: Pengajuan Daftar Usul Pengajuan Angka Kredit, Penilaian Daftar Usul Pengajuan Angka Kredit', 'parent' => '800.1.4'],
                ['kode' => '800.1.5', 'nama' => 'Kinerja Aparatur Sipil Negara', 'parent' => '800.1'],
                ['kode' => '800.1.5.1', 'nama' => 'Hasil Penilaian Kinerja dan Standar Kerja', 'parent' => '800.1.5'],
                ['kode' => '800.1.5.2', 'nama' => 'Pengelolaan Database dan Analisis Sistem Informasi Kinerja', 'parent' => '800.1.5'],
                ['kode' => '800.1.5.3', 'nama' => 'Evaluasi dan Pemantauan Penilaian Kinerja dan Standar Kinerja', 'parent' => '800.1.5'],
                ['kode' => '800.1.6', 'nama' => 'Kode Etik, Disiplin, Pemberhentian dan Pensiun ASN', 'parent' => '800.1'],
                ['kode' => '800.1.6.1', 'nama' => 'Kode Etik Pegawai', 'parent' => '800.1.6'],
                ['kode' => '800.1.6.2', 'nama' => 'Disiplin', 'parent' => '800.1.6'],
                ['kode' => '800.1.6.3', 'nama' => 'Pemberhentian Dengan Hormat', 'parent' => '800.1.6'],
                ['kode' => '800.1.6.4', 'nama' => 'Pemberhentian Dengan Tidak Hormat', 'parent' => '800.1.6'],
                ['kode' => '800.1.6.5', 'nama' => 'Pemberhentian Sementara', 'parent' => '800.1.6'],
                ['kode' => '800.1.6.6', 'nama' => 'Pensiun ASN Antara lain: Administrasi Pensiun ASN, Penetapan Pensiun ASN, Penetapan Pertimbangan Teknis Pensiun ASN, Pensiun Pejabat Negara dan Janda/ Dudanya', 'parent' => '800.1.6'],
                ['kode' => '800.1.7', 'nama' => 'Bantuan Hukum', 'parent' => '800.1'],
                ['kode' => '800.1.8', 'nama' => 'Status dan Kedudukan Pegawai', 'parent' => '800.1'],
                ['kode' => '800.1.8.1', 'nama' => 'Status Kepegawaian', 'parent' => '800.1.8'],
                ['kode' => '800.1.8.2', 'nama' => 'Kedudukan Kepegawaian', 'parent' => '800.1.8'],
                ['kode' => '800.1.8.3', 'nama' => 'Keberatan Pegawai', 'parent' => '800.1.8'],
                ['kode' => '800.1.8.4', 'nama' => 'Perselisihan/Sengketa Kepegawaian', 'parent' => '800.1.8'],
                ['kode' => '800.1.9', 'nama' => 'Sistem Informasi Kepegawaian', 'parent' => '800.1'],
                ['kode' => '800.1.9.1', 'nama' => 'Pengolahan Data dan Informasi Kepegawaian', 'parent' => '800.1.9'],
                ['kode' => '800.1.9.2', 'nama' => 'Pengembangan Sistem Informasi Kepegawaian', 'parent' => '800.1.9'],
                ['kode' => '800.1.9.3', 'nama' => 'Pengembangan Sistem Pengelolaan Arsip Kepegawaian Elektonik', 'parent' => '800.1.9'],
                ['kode' => '800.1.9.4', 'nama' => 'Sistem Pengelolaan Arsip Kepegawaian Fisik', 'parent' => '800.1.9'],
                ['kode' => '800.1.10', 'nama' => 'Pengawasan dan Pengendalian', 'parent' => '800.1'],
                ['kode' => '800.1.10.1', 'nama' => 'Formasi, Pengadaan dan Pasca Diklat', 'parent' => '800.1.10'],
                ['kode' => '800.1.10.2', 'nama' => 'Kepangkatan, Pengangkatan, dan Pemberhentian Dalam Jabatan', 'parent' => '800.1.10'],
                ['kode' => '800.1.10.3', 'nama' => 'Gaji dan Tunjangan, Kesejahteraan dan Kinerja', 'parent' => '800.1.10'],
                ['kode' => '800.1.10.4', 'nama' => 'Kode Etik, Disiplin, Pemberhentian dan Pensiun ASN', 'parent' => '800.1.10'],
                ['kode' => '800.1.10.5', 'nama' => 'Laporan Hasil Pengawasan dan Pengendalian', 'parent' => '800.1.10'],
                ['kode' => '800.1.10.6', 'nama' => 'Sanggahan terhadap Permasalahan Tenaga Honorer', 'parent' => '800.1.10'],
                ['kode' => '800.1.11', 'nama' => 'Administrasi Pegawai', 'parent' => '800.1'],
                ['kode' => '800.1.11.1', 'nama' => 'Surat Perintah Dinas/Surat Tugas', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.2', 'nama' => 'Cuti Sakit', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.3', 'nama' => 'Cuti Bersalin', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.4', 'nama' => 'Cuti Tahunan', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.5', 'nama' => 'Cuti Alasan Penting', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.6', 'nama' => 'Cuti Besar', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.7', 'nama' => 'Cuti Di luar Tanggungan Negara', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.8', 'nama' => 'Karpeg/KPE/Karis/Karsu', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.9', 'nama' => 'Keanggotaan Organisasi Profesi/Kedinasan', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.10', 'nama' => 'Laporan Pajak Penghasilan Pribadi (LP2P)', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.11', 'nama' => 'Keterangan Penerimaan Pembayaran Penghasilan Pegawai (KP4)', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.12', 'nama' => 'Daftar Urut Kepangkatan (DUK)', 'parent' => '800.1.11'],
                ['kode' => '800.1.11.13', 'nama' => 'Pengurusan Kenaikan Gaji Berkala, Mutasi Gaji/ tunjangan', 'parent' => '800.1.11'],
                ['kode' => '800.1.12', 'nama' => 'Kesejahteraan Pegawai', 'parent' => '800.1'],
                ['kode' => '800.1.12.1', 'nama' => 'Pemeliharaan Kesehatan Pegawai', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.2', 'nama' => 'Asuransi Pegawai/BPJS', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.3', 'nama' => 'Tabungan Perumahan', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.4', 'nama' => 'Bantuan Sosial', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.5', 'nama' => 'Pakaian Dinas', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.6', 'nama' => 'Layanan Pegawai yang Meninggal Karena Dinas', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.7', 'nama' => 'Pemberian Tali Kasih', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.8', 'nama' => 'Pemberian Piagam Penghargaan dan Tanda Jasa', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.9', 'nama' => 'Olahraga dan Rekreasi', 'parent' => '800.1.12'],
                ['kode' => '800.1.12.10', 'nama' => 'Rekam Media', 'parent' => '800.1.12'],
                ['kode' => '800.1.13', 'nama' => 'Administrasi Perseorangan', 'parent' => '800.1'],
                ['kode' => '800.1.13.1', 'nama' => 'Pegawai Negeri Sipil (PNS)', 'parent' => '800.1.13'],
                ['kode' => '800.1.13.2', 'nama' => 'Pegawai Pemerintah dengan Perjanjian Kerja (PPPK)', 'parent' => '800.1.13'],
                ['kode' => '800.1.13.3', 'nama' => 'Pejabat Negara dan pejabat lainnya yang disetarakan', 'parent' => '800.1.13'],
                ['kode' => '800.1.13.4', 'nama' => 'Sekretaris Daerah', 'parent' => '800.1.13'],
                ['kode' => '800.1.13.5', 'nama' => 'ASN berjasa/terlibat dalam peristiwa berskala nasional', 'parent' => '800.1.13'],
                ['kode' => '800.1.14', 'nama' => 'Penilaian Kompetensi', 'parent' => '800.1'],
                ['kode' => '800.1.14.1', 'nama' => 'Penilaian Kompetensi', 'parent' => '800.1.14'],
                ['kode' => '800.1.14.2', 'nama' => 'Hasil Penilaian Kompetensi', 'parent' => '800.1.14'],

                ['kode' => '800.2', 'nama' => 'PENDIDIKAN DAN PELATIHAN', 'parent' => '800'],
                ['kode' => '800.2.1', 'nama' => 'Kebijakan di bidang Pendidikan dan Pelatihan yang dilakukan oleh Pemerintah Daerah', 'parent' => '800.2'],
                ['kode' => '800.2.2', 'nama' => 'Pendidikan dan Pelatihan', 'parent' => '800.2'],
                ['kode' => '800.2.2.1', 'nama' => 'Sistem Informasi program dan pembinaan diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.2', 'nama' => 'Pedoman-pedoman kediklatan', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.3', 'nama' => 'Kurikulum-kurikulum diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.4', 'nama' => 'Modul-modul diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.5', 'nama' => 'Panduan fasilitator', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.6', 'nama' => 'Saran/rekomendasi penyelenggaraan diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.7', 'nama' => 'Notulen sosialisasi/Rapat Koordinasi Kebijakan Diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.8', 'nama' => 'Monitoring dan evaluasi program dan pembinaan diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.2.9', 'nama' => 'Konsultasi, advokasi, asistensi diklat', 'parent' => '800.2.2'],
                ['kode' => '800.2.3', 'nama' => 'Widyaiswara', 'parent' => '800.2'],
                ['kode' => '800.2.3.1', 'nama' => 'Seleksi dan pengembangan Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.3.2', 'nama' => 'Sertifikasi Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.3.3', 'nama' => 'Monitoring dan evaluasi Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.3.4', 'nama' => 'Penilaian Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.3.5', 'nama' => 'Konsultasi, advokasi, asistensi Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.3.6', 'nama' => 'Sistem Informasi Pembinaan Widyaiswara', 'parent' => '800.2.3'],
                ['kode' => '800.2.4', 'nama' => 'Penyelenggaraan Diklat', 'parent' => '800.2'],
                ['kode' => '800.2.4.1', 'nama' => 'Perencanaan; peserta, pengajar, penjadwalan Penyelenggaraan Diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.2', 'nama' => 'Penyelenggaraan Penyelenggaraan Diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.3', 'nama' => 'Konsultasi, advokasi, asistensi penyelenggaraan diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.4', 'nama' => 'Pengembangan bahan ajar dan metodologi pembelajaran', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.5', 'nama' => 'Sistem informasi diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.6', 'nama' => 'Monitoring Penyelenggara Diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.4.7', 'nama' => 'Monitoring dan evaluasi Pasca diklat', 'parent' => '800.2.4'],
                ['kode' => '800.2.5', 'nama' => 'Alumni', 'parent' => '800.2'],

                // Data KEUANGAN 
                ['kode' => '900', 'nama' => 'KEUANGAN', 'parent' => null],
                ['kode' => '900.1', 'nama' => 'KEUANGAN DAERAH', 'parent' => '900'],
                ['kode' => '900.1.1', 'nama' => 'Rencana Anggaran Pendapatan dan Belanja Daerah (RAPBD) dan Anggaran Pendapatan dan Belanja Daerah Perubahan (APBD-P)', 'parent' => '900.1'],
                ['kode' => '900.1.1.1', 'nama' => 'Penyusunan Prioritas Plafon Anggaran (PPA)', 'parent' => '900.1.1'],
                ['kode' => '900.1.1.2', 'nama' => 'Penyusunan Rencana Kerja Anggaran Satuan Kerja Perangkat Daerah (RKASKPD)', 'parent' => '900.1.1'],
                ['kode' => '900.1.1.3', 'nama' => 'Penyampaian Rancangan Anggaran Pendapatan dan Belanja Daerah kepada Dewan Perwakilan', 'parent' => '900.1.1'],
                ['kode' => '900.1.1.4', 'nama' => 'Anggaran Pendapatan dan Belanja Daerah Perubahan (RAPBD-P)', 'parent' => '900.1.1'],
                ['kode' => '900.1.2', 'nama' => 'Penyusunan Anggaran', 'parent' => '900.1'],
                ['kode' => '900.1.2.1', 'nama' => 'Musyawarah Rencana Pembangunan (Musrenbang) kecamatan', 'parent' => '900.1.2'],
                ['kode' => '900.1.2.2', 'nama' => 'Musyawarah Rencana Pembangunan (Musrenbang) Kota', 'parent' => '900.1.2'],
                ['kode' => '900.1.2.3', 'nama' => 'Rancangan Dokumen Pelaksanaan Anggaran (RDPA) SKPD yang telah disetujui Sekretaris Daerah', 'parent' => '900.1.2'],
                ['kode' => '900.1.2.4', 'nama' => 'Dokumen Pelaksanaan Anggaran (DPA) SKPD yang telah disahkan oleh Pejabat Pengelola Keuangan Daerah (PPKD)', 'parent' => '900.1.2'],
                ['kode' => '900.1.3', 'nama' => 'Pelaksanaan Anggaran', 'parent' => '900.1'],
                ['kode' => '900.1.3.1', 'nama' => 'Surat Penyedia Dana (SPP, SPM dan SP2D): UP, GU, TU, LS', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.2', 'nama' => 'Pendapatan', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.3', 'nama' => 'Belanja', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.4', 'nama' => 'Pembiayaan Daerah', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.5', 'nama' => 'Dokumen Penatausahaan Keuangan', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.6', 'nama' => 'Pertanggungjawaban Penggunaan Dana', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.7', 'nama' => 'Daftar Gaji', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.8', 'nama' => 'Kartu Gaji', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.9', 'nama' => 'Data Rekening Bendahara Umum Daerah (BUD)', 'parent' => '900.1.3'],
                ['kode' => '900.1.3.10', 'nama' => 'Laporan Keuangan', 'parent' => '900.1.3'],
                ['kode' => '900.1.4', 'nama' => 'Pinjaman/Hibah Luar Negeri', 'parent' => '900.1'],
                ['kode' => '900.1.4.1', 'nama' => 'Permohonan Pinjaman/Hibah Luar Negeri (Blue Book)', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.2', 'nama' => 'Dokumen Kesanggupan Negara Donor untuk Membiayai (Green Book)', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.3', 'nama' => 'Dokumen Memorandum of Understanding (MoU), dan dokumen sejenisnya', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.4', 'nama' => 'Dokumen Loan Agremeent (PHLN) Antara lain: Draft Agreement, Legal Opinion, Surat Menyurat dengan Lender', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.5', 'nama' => 'Alokasi dan Relokasi Penggunaan Dana Luar Negeri, antara lain: usulan luncuran dana', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.6', 'nama' => 'Aplikasi Penarikan Dana BLN berikut lampirannya', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.7', 'nama' => 'Dokumen Otorisasi Penarikan Dana (Payment Advice)', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.8', 'nama' => 'Dokumen Realisasi Pencairan Dana Bantuan Luar Negeri, yaitu: Surat Perintah Pencairan Dana, SPM beserta lampirannya, a.l.: SPP, Kontrak, BA, dan data pendukung lainnya.', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.9', 'nama' => 'Replenishment (Permintaan Penarikan Dana dari Negara Donor) meliputi antara lain: No Objection Letter (NOL), Project Implementation, Notification of Contract, Withdrawal Authorization (WA),', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.10', 'nama' => 'Staff Appraisal Report', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.11', 'nama' => 'Report / Laporan', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.12', 'nama' => 'Laporan Hutang Daerah', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.13', 'nama' => 'Completion Report / Annual Report', 'parent' => '900.1.4'],
                ['kode' => '900.1.4.14', 'nama' => 'Ketentuan/Peraturan yang menyangkut Pinjaman/Hibah Luar Negeri', 'parent' => '900.1.4'],
                ['kode' => '900.1.5', 'nama' => 'Pengelolaan APBD/Dana Pinjaman/Hibah Luar Negeri (PHLN)', 'parent' => '900.1'],
                ['kode' => '900.1.6', 'nama' => 'Sistem Akuntansi Keuangan Daerah (SAKD)', 'parent' => '900.1'],
                ['kode' => '900.1.6.1', 'nama' => 'Manual Implementasi Sistem Akuntansi Keuangan Daerah (SAKD)', 'parent' => '900.1.6'],
                ['kode' => '900.1.6.2', 'nama' => 'Dokumen Kebijakan Akuntansi', 'parent' => '900.1.6'],
                ['kode' => '900.1.6.3', 'nama' => 'Arsip Data Komputer dan Berita Acara Rekonsiliasi', 'parent' => '900.1.6'],
                ['kode' => '900.1.6.4', 'nama' => 'Laporan Realisasi Anggaran dan Neraca Bulanan /Triwulanan /Semesteran', 'parent' => '900.1.6'],
                ['kode' => '900.1.7', 'nama' => 'Penyaluran Anggaran Tugas Pembantuan', 'parent' => '900.1'],
                ['kode' => '900.1.7.1', 'nama' => 'Surat Penetapan Pemimpin Proyek/Bagian Proyek, Bendahara, atas Penggunaan Anggaran Kegiatan Pembantuan, termasuk Specimen Tanda Tangan', 'parent' => '900.1.7'],
                ['kode' => '900.1.7.2', 'nama' => 'Berkas Permintaan Pembayaran (SPP) dan lampirannya: SPP-SPP-Daftar Perincian Penggunaan SPPR-SPDR-L, SPM-LS, SPM-DU, bilyet giro, SPM Nihil, Penagihan/Invoice, Faktur Pajak, Bukti Penerimaan Kas/Bank beserta Bukti Pendukungnya a.l.: Copy Faktur Pajak dan Nota Kredit Bank, Permintaan Pelayanan Jasa/Service Report dan Berita Acara Penyelesaian Pekerjaan', 'parent' => '900.1.7'],
                ['kode' => '900.1.7.3', 'nama' => 'Buku Rekening Bank', 'parent' => '900.1.7'],
                ['kode' => '900.1.7.4', 'nama' => 'Keputusan Pembukuan Rekening', 'parent' => '900.1.7'],
                ['kode' => '900.1.7.5', 'nama' => 'Pembukuan anggaran terdiri antara lain: Buku Kas Umum (BKU), Buku Pembantu, Register dan Buku Tambahan, Daftar Pembukuan Pencairan/Pengeluaran (DPP), Daftar Himpunan Pencairan (DHP), dan Rekening Koran', 'parent' => '900.1.7'],
                ['kode' => '900.1.8', 'nama' => 'Penerimaan Anggaran Tugas Pembantuan', 'parent' => '900.1'],
                ['kode' => '900.1.8.1', 'nama' => 'Berkas Penerimaan Keuangan Pelaksanaan dan Tugas Pembantuan termasuk Dana Sisa atau Pengeluaran lainnya', 'parent' => '900.1.8'],
                ['kode' => '900.1.8.2', 'nama' => 'Berkas Penerimaan Pajak termasuk PPh 21, PPh 22, PPh 23, dan PPn dan Denda Keterlambatan Menyelesaikan Pekerjaan', 'parent' => '900.1.8'],
                ['kode' => '900.1.9', 'nama' => 'Penyusunan Anggaran Pilkada dan Biaya Bantuan Pemilu Dari APBD meliputi: Kebijakan Keuangan Pilkada dan Penyusunan Anggaran Bantuan Pemilu, Peraturan/Pedoman/Standar Belanja Pegawai, Barang dan Jasa, Operasional dan Kontingensi untuk Biaya Pilkada dan Bantuan Pemilu, Bahan Usulan Rencana Kegiatan dan Anggaran (RKA) Pilkada KPUD dan Panwasda Kota, PPK, PPS, KPPS dan Permohonan Pengajuan RKA KPUD dan Panwas, Berkas Pembahasan RKA Pilkada dan Bantuan Pemilu, Rencana Anggaran Satuan Kerja (RASK) Pilkada dan Bantuan Pemilu Kota, Dokumen Rancangan Anggaran Satuan Kerja (DRASK) Pilkada KPUD dan Panwas Kota dan Bantuan Biaya Pemilu dari APBD, Berkas Pembentukan Dana Cadangan Pilkada, Bahan Rapat Rancangan Peraturan Daerah tentang Pilkada, dan Bantuan Biaya Pemilu dari APBD, Nota Persetujuan DPRD tentang Perda APBD Pilkada dan Bantuan Biaya Pemilu dari APBD', 'parent' => '900.1'],
                ['kode' => '900.1.10', 'nama' => 'Pelaksanaan Anggaran PILKADA dan Anggaran Biaya', 'parent' => '900.1'],
                ['kode' => '900.1.10.1', 'nama' => 'Berkas Penetapan Bendahara dan Atasan Langsung Bendahara KPUD, Bendahara Panwasda dan Bendahara pada Panitia Pilkada dan Pemilu', 'parent' => '900.1.10'],
                ['kode' => '900.1.10.2', 'nama' => 'Berkas Penerimaan Komisi, Rabat Pembayaran Pengadaan Jasa, Bunga, Pelaksanaan Pilkada/Pemilu', 'parent' => '900.1.10'],
                ['kode' => '900.1.10.3', 'nama' => 'Berkas setor Pilkada/Pemilu sisa termasuk dana setor komisi pengadaan barang/jasa, rabat, bunga, jasa giro Berkas Penyaluran Biaya Pemilu termasuk diantaranya Bukti Transfer Bank', 'parent' => '900.1.10'],
                ['kode' => '900.1.10.4', 'nama' => 'Pedoman Dokumen Penyediaan Pembiayaan Kegiatan Operasional (PPKO) Pemilu termasuk Perubahan/Pergeseran/Revisinya', 'parent' => '900.1.10'],
                ['kode' => '900.1.11', 'nama' => 'Pemeriksaan/Pengawasan Keuangan Daerah', 'parent' => '900.1'],
                ['kode' => '900.1.11.1', 'nama' => 'Laporan Hasil Pemeriksaan Badan Pemeriksa Keuangan Republik Indonesia atas Laporan Keuangan', 'parent' => '900.1.11'],
                ['kode' => '900.1.11.2', 'nama' => 'Hasil Pengawasan dan Pemeriksaan Internal', 'parent' => '900.1.11'],
                ['kode' => '900.1.11.3', 'nama' => 'Laporan Aparat Pemeriksa Fungsional', 'parent' => '900.1.11'],
                ['kode' => '900.1.11.4', 'nama' => 'Dokumen Penyelesaian Kerugian Daerah', 'parent' => '900.1.11'],
                ['kode' => '900.1.12', 'nama' => 'Anggaran Daerah', 'parent' => '900.1'],
                ['kode' => '900.1.12.1', 'nama' => 'Anggaran Daerah', 'parent' => '900.1.12'],
                ['kode' => '900.1.12.2', 'nama' => 'Dukungan Teknis Anggaran Daerah', 'parent' => '900.1.12'],
                ['kode' => '900.1.13', 'nama' => 'Pendapatan dan Investasi Daerah', 'parent' => '900.1'],
                ['kode' => '900.1.13.1', 'nama' => 'Pajak Daerah dan Retribusi Daerah Antara lain: fasilitasi pelaksanaan kebijakan standardisasi pajak daerah dan retribusi daerah, penyiapan bahan perumusan bimbingan teknis pajak daerah dan retribusi daerah, penyiapan bahan perumusan analisis dan evaluasi, pemantauan pajak daerah dan penyiapan retribusi bahan daerah, perumusan kebijakan fasilitasi pemberian insentif pajak daerah dan retribusi daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.2', 'nama' => 'Badan Usaha Milik Daerah Antara lain: fasilitasi serta bimbingan teknis di bidang usaha milik daerah lembaga keuangan, fasilitas serta bimbingan teknis di bidang badan usaha milik daerah lembaga non keuangan, penyiapan pelaksanaan monitoring dan evaluasi badan usaha milik daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.3', 'nama' => 'Badan Layanan Umum Daerah Antara lain: analisis, standardisasi teknis, fasilitasi serta bimbingan teknis, pemantauan dan evaluasi di bidang pola pengelolaan keuangan badan layanan umum daerah, Pembinaan pelaksanaan kebijakan, standardisasi teknis, prosedur dan kriteria, fasilitasi serta bimbingan teknis penerapan pola pengelolaan keuangan keuangan badan layanan umum daerah, Penyiapan pelaksanaan monitoring dan evaluasi pola pengelolaan keuangan badan layanan umum daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.4', 'nama' => 'Pengelolaan Kekayaan Daerah Antara lain: fasilitasi serta bimbingan teknis pengelolaan kekayaan, Fasilitasi serta bimbingan teknis investasi daerah, Penyiapan pelaksanaan monitoring dan evaluasi pengelolaan kekayaan dan investasi daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.5', 'nama' => 'Pinjam Dan Obligasi Daerah Antara lain: fasilitasi pelaksanaan kebijakan pinjaman dan hibah kepada pemerintah daerah dan/atau badan usaha milik daerah, Fasilitasi pelaksanaan kebijakan daerah, Fasilitasi obligasi pelaksanaan kebijakan dana bergulir yang bersumber dari APBN, Bimbingan teknis obligasi daerah, dana bergulir serta penyertaan modal daerah, Penyiapan pelaksanaan monitoring dan evaluasi pinjaman dan hibah, obligasi daerah, dan dana bergulir, dan penyertaan modal daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.6', 'nama' => 'Surat Setoran Pajak (SSP) Daerah Pajak Kendaraan Bermotor', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.7', 'nama' => 'Surat Setoran Pajak (SSP) Daerah Pajak Bea Balik Nama Kendaraan Bermotor (BBNKB)', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.8', 'nama' => 'Surat Setoran Pajak (SSP) Daerah Pajak Bahan Bakar Kendaraan Bermotor (PBBKB)', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.9', 'nama' => 'Surat Setoran Pajak (SSP) Daerah Pajak Air Permukaan', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.10', 'nama' => 'Surat Setoran Pajak (SSP) Daerah Pajak Rokok', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.11', 'nama' => 'Surat Ketetapan Retribusi Daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.12', 'nama' => 'Bukti Pembayaran Retribusi Jasa Umum', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.13', 'nama' => 'Bukti Pembayaran Retribusi Jasa Usaha', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.14', 'nama' => 'Bukti Pembayaran Retribusi Perizinan Tertentu', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.15', 'nama' => 'Bukti Pembayaran Retribusi Pengendalian Lalu Lintas', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.16', 'nama' => 'Bukti Pembayaran Retribusi Perpanjangan Izin Mempekerjakan Tenaga Kerja Asing (IMTA)', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.17', 'nama' => 'Bukti Penerimaan Masyarakat', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.18', 'nama' => 'Dokumen Rasionalitas Hasil Pengelolaan Kekayaan Daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.19', 'nama' => 'Bukti Penerimaan SKPD dari Badan Pengelolaan Pendapatan Daerah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.20', 'nama' => 'Bukti Penerimaan dari Pengelolaan Dana Bergulir', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.21', 'nama' => 'Bukti Penerimaan Bunga dan atau Jasa Giro pada Bank', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.22', 'nama' => 'Pajak Bumi Bangunan (PBB)', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.23', 'nama' => 'Bea Perolehan Hak Atas Tanah dan Bangunan (BPHTB)', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.24', 'nama' => 'Hotel', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.25', 'nama' => 'Restoran', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.26', 'nama' => 'Hiburan', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.27', 'nama' => 'Reklame', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.28', 'nama' => 'Penerangan Jalan', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.29', 'nama' => 'Parkir', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.30', 'nama' => 'Air Tanah', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.31', 'nama' => 'Sarang Burung Walet', 'parent' => '900.1.13'],
                ['kode' => '900.1.13.32', 'nama' => 'Mineral', 'parent' => '900.1.13'],
                ['kode' => '900.1.14', 'nama' => 'Fasilitasi Dana Perimbangan', 'parent' => '900.1'],
                ['kode' => '900.1.14.1', 'nama' => 'Fasilitasi Dana Alokasi Umum Antara lain: Koordinasi penyiapan data dasar penghitungan, dan rekonsiliasi dana alokasi umum, Sosialisasi dan supervisi dana alokasi umum, Penyiapan pelaksanaan monitoring dan evaluasi dana alokasi umum', 'parent' => '900.1.14'],
                ['kode' => '900.1.14.2', 'nama' => 'Fasilitasi Dana Alokasi Khusus Antara lain: Koordinasi penyiapan data dasar, Sosialisasi dan supervisi dana alokasi khusus, penyiapan pelaksanaan monitoring, evaluasi dana alokasi khusus, Penyiapan pelaksanaan monitoring, evaluasi dana alokasi khusus', 'parent' => '900.1.14'],
                ['kode' => '900.1.14.3', 'nama' => 'Dana Bagi Hasil Pajak dan Sumber Daya Alam Antara lain: Koordinasi penyiapan data dasar perhitungan, dan rekonsiliasi dana bagi hasil pajak dan sumber daya alam, Sosialisasi dan supervisi dana bagi hasil pajak dan sumber daya alam, Penyiapan pelaksanaan monitoring dan evaluasi dana bagi hasil pajak dan sumber daya alam', 'parent' => '900.1.14'],
                ['kode' => '900.1.14.4', 'nama' => 'Dana Otonomi Khusus dan Dana Transfer Lainnya Sosialisasi Antara lain: dan supervisi dana otonomi khusus, Sosialisasi dan supervisi dan transfer lainnya, Pelaksanaan monitoring dan evaluasi dan otonomi khusus dan dana transfer lainnya', 'parent' => '900.1.14'],
                ['kode' => '900.1.14.5', 'nama' => 'Dukungan Teknis Fasilitasi Dana Perimbangan Antara lain: Penyiapan sinkronisasi kebijakan dan perimbangan, Penyiapan dukungan teknis dana perimbangan, Penyiapan data dan penyusunan informasi laporan untuk dana perimbangan', 'parent' => '900.1.14'],
                ['kode' => '900.1.15', 'nama' => 'Pelaksanaan Dan Pertanggungjawaban Keuangan Daerah', 'parent' => '900.1'],
                ['kode' => '900.1.15.1', 'nama' => 'Akuntansi Dan Pertanggungjawaban Keuangan Daerah Antara lain: Fasilitasi serta bimbingan teknis di bidang akuntansi pertangungjawaban daerah, rancangan Penyiapan peraturan pertanggungjawaban dan keuangan evaluasi daerah keuangan daerah', 'parent' => '900.1.15'],
                ['kode' => '900.1.15.2', 'nama' => 'Pembinaan Kinerja dan Kapasitas Pengelolaan Keuangan Daerah Antara lain: Fasilitasi serta bimbingan teknis di bidang pembinaan kinerja dan kapasitas pengelolaan daerah, rancangan Penyiapan peraturan keuangan evaluasi daerah pertangungjawaban keuangan daerah', 'parent' => '900.1.15'],
                ['kode' => '900.1.15.3', 'nama' => 'Pembinaan dan Evaluasi Pengelolaan Keuangan Daerah Antara lain: Fasilitasi serta bimbingan teknis di bidang pembinaan dan evaluasi pengelolaan keuangan daerah, Penyiapan evaluasi rancangan peraturan daerah pertangungjawaban keuangan daerah', 'parent' => '900.1.15'],
                ['kode' => '900.1.15.4', 'nama' => 'Kajian Kebijakan dan Bantuan Keterangan Ahli Antara lain: Penyiapan bahan bantuan keterangan ahli di bidang keuangan daerah, Penyiapan evaluasi rancangan peraturan daerah pertanggungjawaban keuangan daerah', 'parent' => '900.1.15'],
                ['kode' => '900.1.15.5', 'nama' => 'Data Informasi dan Pengelolaan Keuangan Daerah Antara lain: Penyiapan sinkronisasi kebijakan pelaksanaan pertangungjawaban pelaksanaan keuangan daerah, Penyiapan data dan informasi untuk penyusunan laporan pertangungjawaban pelaksanaan keuangan daerah, Pengelolaan sistem informasi pengelolaan keuangan daerah', 'parent' => '900.1.15'],

            ];


        $kodeToId = [];

        foreach ($data as $item) {
            $parentId = $item['parent'] ? ($kodeToId[$item['parent']] ?? null) : null;

            $record = KlasifikasiSurat::create([
                'kode' => $item['kode'],
                'nama' => $item['nama'],
                'parent_id' => $parentId,
            ]);

            $kodeToId[$item['kode']] = $record->id;
        }
    }
}
